# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Josh Meek'
tagline:          'Software Developer'
description:      'Development journal, project repository, and occasional blog of <a href="https://twitter.com/JoshM33k" target="_blank">@JoshM33k</a>.'
url:              http://joshM33k.github.io
baseurl:          /

author:
  name:           'Josh Meek'
  url:            https://twitter.com/JoshM33k

paginate:         5

# Custom vars
version:          0.1.1

github:
  repo:           https://github.com/JoshM33k/joshM33k.github.io
